FROM python:3.8-slim

WORKDIR /app

RUN \
  pip install -U pip && pip install pipenv && \
  rm -rf /var/lib/apt/lists/*

COPY bin /app/bin
COPY datastore_viewer /app/datastore_viewer
COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

ENV PYTHONPATH .

ENTRYPOINT ["bin/datastore-viewer"]
